services:
  package:
    build:
      context: .
      secrets:
        - github_token
    volumes:
      - ./src:/package/src
      - ./tests:/package/tests
    command: tail -f /dev/null  # container runs indefinitely

secrets:
  github_token:
    environment: GITHUB_TOKEN
